# Generated by Django 6.0.4 on 2026-04-26 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_document"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneratedImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("model", models.CharField(max_length=120)),
                ("prompt", models.TextField()),
                ("width", models.IntegerField(default=1024)),
                ("height", models.IntegerField(default=1024)),
                ("input_image", models.FileField(blank=True, null=True, upload_to="generated_images/input/")),
                ("output_image", models.FileField(upload_to="generated_images/output/")),
                ("mime_type", models.CharField(default="image/png", max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
